name: dr
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 8.2.10+43

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  badges: ^2.0.2
  biometric_storage: ^4.1.1
  built_collection: ^5.1.0
  built_redux:
    git:
      url: https://github.com/miDeb/built_redux.git
      ref: nnbd
  built_value: ^8.0.2
  charts_flutter:
    git:
      url: https://github.com/miDeb/charts
      ref: select_nearest
      path: charts_flutter
  collapsible_sidebar:
    path: packages/collapsible_sidebar/
  collection: ^1.15.0
  cookie_jar: ^3.0.0-beta2
  deleteable_tile: ^0.0.1-nullsafety.1
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0-beta1
  dynamic_theme:
    path: packages/dynamic_theme/
  flutter:
    sdk: flutter
  flutter_built_redux:
    git:
      url: https://github.com/miDeb/flutter_built_redux.git
      ref: nnbd
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.0.3
  flutter_widget_from_html_core: ^0.8.5+3
  fuzzy: ^0.4.0-nullsafety.0
  hive: ^2.0.0
  http: ^0.13.0
  intl: ^0.17.0-nullsafety.2
  mocktail: ^0.3.0
  mutex: ^3.0.0
  open_file:
    git:
      url: https://github.com/miDeb/open_file.git
      ref: master
  package_info_plus: ^1.3.0
  path_provider: ^2.0.0-nullsafety
  quill_delta: ^3.0.0-nullsafety.2
  quill_delta_viewer:
    path: packages/quill_delta_viewer/
  responsive_scaffold:
    path: packages/responsive_scaffold/
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.1
  shared_preferences: ^2.0.15
  tuple: ^2.0.0
  uni_links:
    git:
      url: https://github.com/miDeb/uni_links.git
      ref: modernized
      path: uni_links/
  url_launcher: ^6.1.0

dependency_overrides:
  file: ^6.1.4
  fwfh_text_style: ^2.22.08+1

dev_dependencies:
  build_runner: ^2.1.10
  built_value_generator: ^8.0.2
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  lint: ^1.5.1
  matcher: ^0.12.10-nullsafety.3
  msix: ^3.6.1
  quiver: ^3.0.0-nullsafety.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/index.png"

flutter_native_splash:
  color: "fafafa"
  color_dark: "303030"
  image: "assets/4.0x/splash-light.png"
  image_dark: "assets/4.0x/splash-dark.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

msix_config:
  display_name: Digitales Register
  publisher_display_name: Michael Debertol
  identity_name: 2097MichaelDebertol.DigitalesRegister
  publisher: CN=2508760A-808B-4829-867A-4DB53593750E
  msix_version: 8.2.9.0
  logo_path: assets/4.0x/transparent.png
  architecture: x64
  capabilities: "internetClient"
